apiVersion: v1
kind: Service
metadata:
  name: taspinn-api-service
  labels:
    run: taspinn-api-service
spec:
  type: NodePort
  ports:
  - port: 5001
    targetPort: 31234
  selector:
    app: taspinn-api